apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-new
  namespace: ai-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
